### ISSUE TITLE
Font definition doesn't match uGUI v0.3

### ISSUE THREAD

**Issue by tisaacs** [AriZuu/ttf2ugui#1]
I'm trying to use the tool to convert fonts, but get errors when I include them.
In uGUI v0.3, the structure definition for a font is:

`
typedef struct
{
   unsigned char* p;
   UG_S16 char_width;
   UG_S16 char_height;
} UG_FONT;
`

But ttf2ugui creates a structure definition with the following format:
`
const UG_FONT font_NAME_SIZE = { (unsigned char*)pointer_to_font, FONT_TYPE_1BPP, charWidth, charHeight, startChar, endChar, Name };
`

Did you modify ugui to use the extra parameters or do I have the wrong version?

Many thanks.

**Comment by AriZuu** [comment]
Your version must be too old. Check out https://github.com/achimdoebler/UGUI/blob/master/ugui.h, the UG_FONT definition there is

`
typedef struct
{
   unsigned char* p;
   FONT_TYPE font_type;
   UG_S16 char_width;
   UG_S16 char_height;
   UG_U16 start_char;
   UG_U16 end_char;
   UG_U8  *widths;
} UG_FONT;
`

**Comment by tisaacs** [comment]
Okay brilliant, thanks. Not sure what happened there.

Appreciate your help & the tool is really useful.
