### ISSUE TITLE
Run on mac

### ISSUE THREAD

**Issue by aupilot** [AriZuu/ttf2ugui#3]
The utility runs on Mac (surprise!), but one needs to install freetype:

brew install freetype

When running, use the full path to the font ttf, e.g.:
./ttf2ugui --font /System/Library/Fonts/Supplemental/Arial.ttf --dpi 140 --size 14 --dump

**Comment by AriZuu** [comment]
Well that is nice to hear !

**Comment by AriZuu** [comment]
I added the instructions to README.md.
