### ISSUE TITLE
Arabic or Persian Fonts

### ISSUE THREAD

**Issue by derakhshani4476** [AriZuu/ttf2ugui#4]
Dear AriZuu,
you've done a great job in this project; I 've just wanted to ask you how to make this project work for Arabic or Persian fonts?

**Comment by AriZuu** [comment]
Hi, unfortunately I have no experience with those fonts so I don't know if library used here requires anything special to get things working. Maybe you could just try it out to see what the results are and maybe provide a pull request for necessary changes ?
