### ISSUE TITLE
Support for simplified Chinese

### ISSUE THREAD

**Issue by jianjinliao** [AriZuu/ttf2ugui#5]
Dear AriZuu,
When I use ugui, I can't support simplified Chinese. I try to use ttf2ugui to convert font, and I can't convert Chinese to C array. Do you have any good suggestions?
  Thank You。

**Comment by AriZuu** [comment]
Can you describe the problem a bit more ? Command arguments you are using and possible error message would be helpful in figuring out what might help.

**Comment by jianjinliao** [comment]
I'm using esp32 + esp-idf + ugui to build UI. I want to display Chinese on the screen,However, ugui does not support Chinese display，I copied a Chinese font of windows and used tt2ugui to convert C：ttf2ugui --font Chinese.ttf --dpi 140 --size 14 --dump
The converted ugui. c  still doesn't have a Chinese font, and there's no way to display Chinese

**Comment by AriZuu** [comment]
Try the --show option in ttf2ugui, ie. something like

ttf2ugui --font Chinese.ttf --size 14 --show Test

That should display an ascii art using given font (if that font is available in Windows maybe I could try it myself also).

**Comment by AriZuu** [comment]
I tried chinese font from here: http://www.font-club.com/dfhei1b-gb_141129.html

The --show option displays something that looks like chinese symbols, but I don't know the language show it's difficult to know if it is correct.

**Comment by jianjinliao** [comment]
Yes, --show the display is in Chinese.I checked that ttf2ugui.c can't convert Chinese characters, which seems to be restricted by -- minchar -- maxchar.Can you re create a branch and remove the conversion restriction?

**Comment by jianjinliao** [comment]
Ttf2ugui seems to convert only Latin characters and symbols.

**Comment by AriZuu** [comment]
What if you try something like
 ./ttf2ugui --font Chinese.ttf --dpi 140 --size 14 --dump --maxchar 500

ie. it is possible to specify maxchar value, default is just to dump visible ascii characters 32 - 126.

**Comment by jianjinliao** [comment]
Thank you for your reply. This problem has been solved.
