### ISSUE TITLE
Windows binaries

### ISSUE THREAD

**Issue by deividAlfa** [AriZuu/ttf2ugui#7]
I've compiled it for windows, it might be a good idea to add it, not everybody knows how to setup a cygwin envirnment, also it's time-consuming.
https://github.com/deividAlfa/ST7789-STM32-uGUI/blob/master/ttf2ugui-win.zip

**Comment by AriZuu** [comment]
I won't be adding binaries to this repo. However, if you write instructions (a HOW-TO-BUILD-ON-WINDOWS.md) I would be more than happy to include it.
